name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v2
        name: Cache dependencies

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install cmake

      - name: Check formatting
        run: cargo fmt --check --all

      - name: Clippy (all features)
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --workspace

      - name: Build
        run: cargo build --verbose --workspace

  build-nix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes

      - uses: cachix/cachix-action@v12
        with:
          name: hyprland-community
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix build .#hypract .#hypract-anyrun --print-build-logs
