name: Build and Cache

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-nix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - hypract
          - hypract-anyrun

    steps:
      - uses: easimon/maximize-build-space@v6
        with:
          overprovision-lvm: true
          remove-android: true
          remove-dotnet: true
          remove-haskell: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Cachix
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Cachix setup
        uses: cachix/cachix-action@v12
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
          name: hyprland-community

      - name: Set default git branch (to reduce log spam)
        run: git config --global init.defaultBranch main

      - name: Build from the matrix
        run: nix build .#${{ matrix.package }} --print-build-logs
